use certifi certs with urllib.request.urlopen() calls (#766)
A few PRs here were blocked today with errors like this in wheel tests:

```text
File "/pyenv/versions/3.13.11/lib/python3.13/urllib/request.py", line 1322, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1032)>
```

example: https://github.com/rapidsai/cuxfilter/pull/764#issuecomment-3843183479

It's no coincidence that this only happened on wheel tests... the wheel testing job here uses an older Linux distribution (RockyLinux 8) where it sometimes takes a few days for certificate updates to propagate as new `ca-certificates` packages.

This proposes the following fixes:

* using `certifi`'s certificate bundle for all `urllib.request.urlopen()` calls in the library
* explicitly declaring the currently-implicit `requests` dependency

## Notes for Reviewers

### This looks like it's adding new dependencies, but it isn't

This project already has a hard runtime dependency on `requests` (though it isn't declaring it):

https://github.com/rapidsai/cuxfilter/blob/16024682155855b88c40723d0f94087e208a35d2/python/cuxfilter/charts/datashader/plots.py#L29

And `requests` has a hard runtime dependency on `certifi` and uses its certificates by default:

https://requests.readthedocs.io/en/latest/user/advanced/#ca-certificates

Authors:
  - James Lamb (https://github.com/jameslamb)

Approvers:
  - Bradley Dice (https://github.com/bdice)

URL: https://github.com/rapidsai/cuxfilter/pull/766