Notebook update: removed spaces in directory name (#400)
Notebook update: removed spaces in directory name which breaks [notebook testing automation](https://github.com/rapidsai/notebooks/blob/branch-22.10/test/test.sh)
```
--------------------------------------------------------------------------------
STARTING: cuxfilter
--------------------------------------------------------------------------------
Running "ipython --colors=NoColor /tmp/tmp.EZ2nDuPYBI.py" on Mon Jun 20 02:44:02 UTC 2022

[22;0t]0;IPython: cuxfilter/notebooks   File "/tmp/tmp.EZ2nDuPYBI.py", line 20
    This application is used to convert notebook files (*.ipynb)
         ^
SyntaxError: invalid syntax
```

Authors:
  - Mike McCarty (https://github.com/mmccarty)

Approvers:
  - Ray Douglass (https://github.com/raydouglass)

URL: https://github.com/rapidsai/cuxfilter/pull/400