use cudf DataFrame constructor instead of from_pandas() (#751)
Nightly builds here are breaking like this:

```text
File /opt/conda/envs/docs/lib/python3.13/site-packages/cuxfilter/sampledata/random_signals.py:47
     44 data["Time"] = [start + datetime.timedelta(minutes=1) * i for i in range(n)]
     46 # Create a dataframe
---> 47 df = cudf.DataFrame.from_pandas(pd.DataFrame(data))

AttributeError: type object 'DataFrame' has no attribute 'from_pandas'
```

([build link](https://github.com/rapidsai/cuxfilter/actions/runs/20613315511/job/59201702539#step:12:1652))

I think because of https://github.com/rapidsai/cudf/pull/20925

This switches to the `cudf.DataFrame` constructor to fix that.

Authors:
  - James Lamb (https://github.com/jameslamb)

Approvers:
  - Ajay Thorve (https://github.com/AjayThorve)

URL: https://github.com/rapidsai/cuxfilter/pull/751